export const QuestionItems = [
  {
    title: 'Когда вы родились ?',
    variantsOptions: [
      'Молчаливое поколение (1925-1943)',
      'Покаление бэби-бумеров (1944-1967)',
      'Покаление X (1957-1984)',
      'Покаление Y - миллениалы (1984-2000)',
      'Покаление Z - зуммеры (2000-2011)',
      'Покаление альфа (c 2011)',
    ],
    iconOptions: [
      '/img/MolchalivoePokolenie.svg',
      '/img/PokolenieBB.svg',
      '/img/PokolenieX.svg',
      '/img/PokolenieY.svg',
      '/img/PokolenieZ.svg',
      '/img/PokolenieAlfa.svg',
    ],
  },
  {
    title: 'Образование',
    variantsOptions: ['Да', 'Нет'],
    selectedOptions: [
      'Школа',
      'Гимназия',
      'ВУЗ',
      'несколько ВУЗ`ов',
      'Магистратура',
      'Аспирантура',
      'Доктанатура',
      'Иное',
    ],
    iconOptions: [
      '/img/SredniaSchool.svg',
      '/img/SredniaGimnazia.svg',
      '/img/Vvuz.svg',
      '/img/VneskolkoVuzov.svg',
      '/img/Vmagistratura.svg',
      '/img/Vaspirantura.svg',
      '/img/Vdoctorantura.svg',
      '/img/Vinoe.svg',
    ],
  },
  {
    title: 'Где вы родились ?',
    variantsOptions: ['Мегаполис', 'Город', 'Иное'],
    iconOptions: ['/img/MegaCity.svg', '/img/City.svg', '/img/InoeMestoRozdenia.svg'],
  },
  {
    title: 'Какая у вас семья ?',
    variantsOptions: ['Полная', 'Мама', 'Папа', 'Без родителей'],
    iconOptions: [
      '/img/PolnaiaFamily.svg',
      '/img/Mom.svg',
      '/img/Papa.svg',
      '/img/BezRoditeley.svg',
    ],
  },
  {
    title: 'Брат/Сестра',
    variantsOptions: ['Братья и сестры', 'Брат/братья', 'Сестра/сестры', 'Никого'],
    iconOptions: [
      '/img/BrothersAndSisters.svg',
      '/img/Brother.svg',
      '/img/Sister.svg',
      '/img/NetBrotherSister.svg',
    ],
  },
  {
    title: 'Женат/Замужем',
    variantsOptions: ['Да', 'Нет'],
    iconOptions: ['/img/DaZenat.svg', '/img/NeZenat.svg'],
  },
  {
    title: 'Дети',
    variantsOptions: ['Сын и дочь', 'Сын', 'Дочь', 'Никого'],
    iconOptions: [
      '/img/SonAndDoch.svg',
      '/img/Son.svg',
      '/img/Dochka.svg',
      '/img/NetDeti.svg',
    ],
  },
  {
    title: 'Работа',
    variantsOptions: [
      'Социальная сфера',
      'Управление',
      'Образование',
      'Медицина',
      'Цифровые технологии',
      'Производство',
      'Искусство',
      'Иное',
      'Нет работы',
    ],
    iconOptions: [
      '/img/SocialSfera.svg',
      '/img/Upravlenie.svg',
      '/img/Obrazovanie.svg',
      '/img/Medicina.svg',
      '/img/DigitalTechnologies.svg',
      '/img/Proizvodstvo.svg',
      '/img/Iskusstvo.svg',
      '/img/InoeSferaWork.svg',
      '/img/InoeSferaWork.svg',
    ],
  },
  {
    title: 'Должность',
    variantsOptions: ['Руководитель', 'Иное'],
    iconOptions: ['/img/Ruckovoditel.svg', '/img/InoeDolznost.svg'],
  },
  {
    title: 'Домашние животные',
    variantsOptions: ['Да', 'Нет'],
    selectedOptions: [
      'Млекопитающие',
      'Земноводные',
      'Насекомые',
      'Молюски',
      'Рыбы',
      'Птицы',
      'Паукообразные',
      'Пресмыкающие',
      'Ракообразные',
    ],
    iconOptions: [
      '/img/Mlekopitauchee.svg',
      '/img/Zemnovodnie.svg',
      '/img/Nasekomoe.svg',
      '/img/Moluski.svg',
      '/img/Fish.svg',
      '/img/Birds.svg',
      '/img/Paukoobraznie.svg',
      '/img/Presmikaushee.svg',
      '/img/Rackoobraznie.svg',
    ],
  },
  {
    title: 'Хобби',
    variantsOptions: ['Да', 'Нет'],
    selectedOptions: [
      'Коллекционирование',
      'Книги',
      'Рукоделие',
      'Кулинария',
      'Садоводство',
      'Искусство',
      'Охота',
      'Рыбалка',
      'Моделизм',
      'Изучение языков',
      'Иное',
    ],
    iconOptions: [
      '/img/Kolleksionirovanie.svg',
      '/img/Books.svg',
      '/img/Rucodelie.svg',
      '/img/Kulinaria.svg',
      '/img/Sadovodstvo.svg',
      '/img/Iskusstvo.svg',
      '/img/Ohota.svg',
      '/img/Ribalka.svg',
      '/img/Modelizm.svg',
      '/img/IzuchenieLanguaches.svg',
      '/img/InoeHobbi.svg',
    ],
  },
  {
    title: 'Питание',
    variantsOptions: ['Традиционное', 'Вегатерионство', 'Мясоедство', 'Иное'],
    iconOptions: [
      '/img/TraditionPitanie.svg',
      '/img/Vegeterianstvo.svg',
      '/img/Miasoedstvo.svg',
      '/img/InoePitanie.svg',
    ],
  },
  {
    title: 'Спорт',
    variantsOptions: ['Да', 'Нет'],
    selectedOptions: [
      'Зимний',
      'Водные',
      'Экстримальные',
      'Боевые искусства',
      'Йога',
      'Акробатика',
      'Тяжелая атлетика',
      'Легкая атлетика',
      'Спортивные игры',
      'Стрелковый',
      'Иное',
    ],
    iconOptions: [
      '/img/WinterSport.svg',
      '/img/Vodnie.svg',
      '/img/Eckstriem.svg',
      '/img/BoevieIskusstva.svg',
      '/img/Yoga.svg',
      '/img/Akrobatika.svg',
      '/img/TiazelaiaAtletika.svg',
      '/img/LegkaiAtletika.svg',
      '/img/SportGame.svg',
      '/img/Ohota.svg',
      '/img/InoeHobbi.svg',
    ],
  },
  {
    title: 'Путешествие',
    variantsOptions: ['Да', 'Нет'],
    selectedOptions: [
      'Европа',
      'Россия',
      'Азия',
      'Америка',
      'Австралия',
      'Северный полюс',
    ],
    iconOptions: [
      '/img/Europe.svg',
      '/img/Russia.svg',
      '/img/Azia.svg',
      '/img/Usa.jpg.svg',
      '/img/Australia.svg',
      '/img/NorthPolus.svg',
      '/img/Australia.svg',
    ],
  },
];
